name: CI

on: push

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.4' # Define the OTP version [required]
          elixir-version: '1.19.0-rc.0-otp-27' # Define the elixir version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: live_state/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - uses: actions/cache@v4
        name: Cache build
        with:
          path: live_state/_build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Install dependencies
        run: mix deps.get
      - name: Run elixir tests
        run: mix test
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: run-integration-tests
          repository: "launchscout/live_state_testbed"
          token: ${{ secrets.TESTBED_PAT}}